apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: muldos/dgs-skeleton:1.2.2
          livenessProbe:
            httpGet:
              path: /health/status
              port: 8080
            initialDelaySeconds: 10
          ports:
            - containerPort: 8080
