apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apijsondb-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: ""
