apiVersion: v1
kind: ReplicationController
metadata:
  name: api-controller
spec:
  replicas: 2
  selector:
    app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: muldos/dgs-skeleton:1.2.2
          livenessProbe:
            httpGet:
              path: /health/status
              port: 8080
            initialDelaySeconds: 10
          ports:
            - containerPort: 8080
