apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-set
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: muldos/dgs-skeleton:1.4.0
          volumeMounts:
            - name: jsondb
              mountPath: /var/db_data

          livenessProbe:
            httpGet:
              path: /health/status
              port: 8080
            initialDelaySeconds: 10
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
      volumes:
        - name: jsondb
          emptyDir: {}
