apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  tls:
    - hosts:
        - api.davidrobin.net
      secretName: tls-secret
  rules:
    - host: api.davidrobin.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-nodeport
                port:
                  number: 80
