# aws ec2 create-volume --availability-zone=eu-west-3b --size=1 --volume-type=gp3 --region eu-west-3 --profile eks
kind: List
apiVersion: v1
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-a
      labels:
        type: custompv
    spec:
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Recycle
      awsElasticBlockStore:
        fsType: ext4
        volumeID: vol-0e3c1c81c2ef65c54
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-b
      labels:
        type: custompv
    spec:
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Recycle
      awsElasticBlockStore:
        fsType: ext4
        volumeID: vol-080b6ca5605a592d8
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-c
      labels:
        type: custompv
    spec:
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Recycle
      awsElasticBlockStore:
        fsType: ext4
        volumeID: vol-021121c08bb656445
